---
- name: This is sample playbook
  hosts: testnodes
  tasks:
    - name: Put the new update '/var/www/html/index.html'.
      copy:
        content: hello world
        dest: /var/www/html/index.html
