- name: Hello World Sample
  hosts: all
  tasks:
   - name: Get user name
     shell: whoami
     register: theuser
   - name: Print out the result
     debug: msg="Logged in at {{ thehost.stdout }}"
