---
- name: Playbook for verifying filesystem
  hosts: all
  tasks:
   - name: Get user name
     shell: whoami
     register: theuser
   - name: Get host name
     shell: hostname
     register: thehost
   - name: Print out the result
     debug: msg="Logged in as {{ theuser.stdout }} at {{ thehost.stdout }}"
