---
- name: This is sample playbook
  hosts: testnodes
  tasks:
    - name: Get datetime from the system
      shell: "date"
      register: current_time
    - name: Put the new update '/var/www/html/jenkins/demo01/index.html'.
      copy:
        content: <h1>Hello, it worked!!!</h1><br>Updated at {{ current_time.stdout }}
        dest: /var/www/html/index.html
