---
- name: This is sample playbook
  hosts: testnodes
  tasks:
    - name: Put the new update '/var/www/html/index.html'.
      copy:
        content: <h1>Hello, it worked!!!</h1><br>Updated at XX/XX/XX XX:XX
        dest: /var/www/html/index.html
